<h1>GALLERY</h1>
<div class="gallery">
    <?php foreach ($pictures as $picture) : ?>
        <div class="photo">
            <div class="userInfo">
                <div class="userName">
                    <img src="<?= $picture['photo_src']; ?>" alt="" class="imgUser">
                    <p><?= $picture['user_pseudo']; ?></p>
                </div>
                <p class="datePhotos"><?= date_format(date_create($picture['created_at']), "d M Y")  ?></p>
            </div>
            <hr>
            <a href="?page=article&id=<?= $picture['id'] ?>">
                <img src="<?= $picture['src'] ?>" alt="<?= $picture['title'] ?>" class="imgArticle">
            </a>
            <p class="titrePhoto"><?= $picture['title'] ?></p>
            <p class="descritpionPhoto"><?= $picture['description'] ?></p>
            <a href="?page=article&id=<?= $picture['id'] ?>" class="lienPhotos">Voir l'article</a>

        </div>
    <?php endforeach; ?>
</div>