<h1>Setting</h1>
<div class="menuAdmin">
  <a data-bs-toggle="collapse" href="#collapseCommentaires">Tableau de bord</a>
  <a data-bs-toggle="collapse" href="#paramCompte">Paramètres compte</a>
  <a data-bs-toggle="collapse" href="#paramCompte">Admin Articles</a>
  <a data-bs-toggle="collapse" href="#collapseCommentaires">Admin comptes</a>
</div>

<div class="paramCompte">
  <h2>Infos</h2>
  <a href="index.php?page=deconnexion" class="btn btn-danger m-1">Déconnexion</a>
  <p><?= $id ?></p>
  <form style="margin:5% 25%" method="POST">
    <div class="mb-3">
      <label for="firstname" class="form-label">Prénom:</label>
      <input type="text" class="form-control" id="firstname" name="firstname" value="<?= $user['firstname'] ?>">
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">Nom:</label>
      <input type="text" class="form-control" id="name" name="name" value="<?= $user['name'] ?>" required>
    </div>
    <div class="mb-3">
      <label for="pseudo" class="form-label">Pseudo:</label>
      <input type="text" class="form-control" id="pseudo" name="pseudo" value="<?= $user['pseudo'] ?>" required>
    </div>
    <div class="mb-3">
      <label for="gender" class="form-label">Genre:</label>
      <select class="form-control" id="gender" name="gender" required>
        <option value="homme" <?php if ($user['gender'] === 'homme') echo 'selected'; ?>>Homme</option>
        <option value="femme" <?php if ($user['gender'] === 'femme') echo 'selected'; ?>>Femme</option>
        <option value="autres" <?php if ($user['gender'] === 'autres') echo 'selected'; ?>>Autres</option>
      </select>
    </div>
    <div class="mb-3">
      <label for="mail" class="form-label">E-mail:</label>
      <input type="email" class="form-control" id="mail" name="mail" value="<?= $user['mail'] ?>" required>
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Mot de passe:</label>
      <input type="password" class="form-control" id="password" name="password" value="<?= $user['password'] ?>" required>
    </div>

    <input type="submit" name="updateInfos" class="form-control" value="Modifier mes informations">
  </form>
</div>