<?php if (!isset($_SESSION['id'])) {
    header("Location: index.php?page=log")
?>

<?php } else { ?>
    <?php foreach ($friends as $friend) : ?>
        <div class="userfollow" id="friend_<?= $friend['id_follow']; ?>">
            <div class="userpseudo">
                <a href="?page=userpage&id=<?= $friend['id_follow'] ?>" class="pseudoLink">
                    <div class="flexUser">
                        <div class="blocPhotoUserFollow">
                            <img src="<?= $friend['photo_src']; ?>" alt="">
                        </div>
                        <?= $friend['user_pseudo']; ?>
                    </div>
                </a>
            </div>
            <div class="followOption">
                <button class="unfollowed  form-control" data-followid="<?= $friend['id_follow']; ?>">Unfollow</button>
                <!-- <button class="  form-control">Discuter</button> -->
            </div>
        </div>
    <?php endforeach; ?>
<?php } ?>
<script>
    $(document).ready(function() {
        $('.unfollowed').click(function(event) {
            event.preventDefault();


            let button = $(this);
            let followId = button.data('followid');
            let userFollow = document.querySelector('#friend_' + followId)
            userFollow.classList.add('transitionUnfollow');
            setTimeout(() => {
                userFollow.style.display = "none";
            }, 300);

            $.ajax({
                type: 'POST',
                url: '?page=follow',
                data: {
                    followId: followId,
                },
            });
        });
    });
</script>