<?php if (!isset($_SESSION['id'])){ 
  header("Location: index.php?page=log")
  ?>

  <?php } else {?>

<?php if ($_SESSION['admin']) { ?>

<h2>Update</h2>
<div class="imgbanniere">
<img src="<?=$picture['src'];?>" alt="<?=$picture['title'];?>">

  </div>



<form style="margin:5%" method="POST">
    <div class="mb-3">
        <label for="title" class="form-label">Titre</label>
        <input type="text" class="form-control" id="title" name="title" value="<?= $picture['title'] ;?>">
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <textarea type="text" class="form-control" id="description" name="description"><?= $picture['description'] ;?></textarea>
    </div>

    <input type="submit" class="form-control" id="submit" name="submit" value="Update Picture">

</form>

<?php } else { ?>
  <p>Vous n'avez pas les autorisations nécéssaires pour accéder à cette page</p>
<?php   }; ?>

<?php } ?>