<h1 style="margin-top:80px; text-align:center">Admin Add Picture</h1>
<form style="margin:5%" method="POST">
    <div class="mb-3">
        <label for="src" class="form-label">Source</label>
        <input type="text" class="form-control" id="src" name="src" placeholder="Source">
    </div>
    <div class="mb-3">
        <label for="title" class="form-label">Titre</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Titre">
    </div>
    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <textarea type="text" class="form-control" id="description" name="description" placeholder="Description"></textarea>
    </div>

    <input type="submit" class="form-control" id="submit" name="submit" value="Add Picture">

</form>

