<div class="gallery search">
    <?php foreach ($pictures as $picture) : ?>
        <div class="photo">
            <p class="datePhotos"><?= date_format(date_create($picture['created_at']), "d M Y")  ?></p>
            <img src="<?= $picture['src'] ?>" alt="<?= $picture['title'] ?>">
            <p class="titrePhoto"><?= $picture['title'] ?></p>
            <p class="descritpionPhoto"><?= $picture['description'] ?></p>
            <a href="?page=article&id=<?= $picture['id'] ?>" class="lienPhotos">Voir l'article</a>

        </div>
    <?php endforeach; ?>
</div>