<?php if (!isset($_SESSION['id'])){ 
  header("Location: index.php?page=log")
  ?>

  <?php } else {?>
    
<div class="header">
  <div class="banniereUser">
    <div class="imgbanniere">
    <img src="<?= $user['src_banner']; ?>" alt="">
  </div>

    <div class="optionUser">

      <div class="photoUser">
        <div class="blocPhotoUser">
        <img src="<?= $user['src_photo']; ?>" alt="">
      </div>
        <p><?= $user['pseudo']; ?></p>
      </div>

      <div class="menuUser">
        <?php
        $id = $_GET['id'];
        if ((int)$_SESSION['id'] !== (int)$id) { ?>
          <?php if ($friends == false) { ?>
            <form method="POST">

              <input type="hidden" name="id_follow" value="<?= $id ?>">
              <input type="submit" name="follow" value="Follow" class="follow">
            </form>
          <?php } else { ?>
            <form method="POST">
              <input type="hidden" name="id_follow" value="<?= $id ?>">
              <input type="submit" name="unfollow" value=" ✓ Follow" class="unfollow">
            </form>
          <?php }  ?>
        <?php } else { ?>
          <div class="">
            <a href="index.php?page=articlelist" class="form-control btnDashBoard">Tableau de Bord</a>
          </div>
        <?php }  ?>
      </div>

    </div>
  </div>


  <hr>
</div>

<div class="gallery">

  <!-- ADD ARTICLE -->
  <?php
  $id = $_GET['id'];
  if ((int)$_SESSION['id'] == (int)$id) :

  ?>
    <div class="addArticle">
      <a class="form-control" data-bs-toggle="collapse" href="#collapseAddPicture"> Add Article</a>

      <div class="collapse" id="collapseAddPicture">
        <form style="margin:5%" method="POST" enctype="multipart/form-data">

          <div class="mb-3">
            <label for="src" class="form-label">Charger une image (moins de 3Mo)</label>
            <?php if (!empty($error)) {
              echo "<p style=\"color : red;\">" . $error . "</p>";
            } ?>

            <input type="file" class="form-control" name="image_file" accept="image/*" required>

          </div>

          <div class="mb-3">
            <label for="title" class="form-label">Titre</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Titre" required>
          </div>

          <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea type="text" class="form-control" id="description" name="description" placeholder="Description"></textarea>
          </div>

          <input type="submit" class="form-control" id="submit" name="submit" value="Add Picture">

        </form>
      </div>

    </div>
  <?php endif; ?>

  <!-- ARTICLE -->
  <?php foreach ($pictures as $picture) : ?>

    <div class="photo">
      <div class="userInfo">
        <div class="userName">
        <div class="blocPhotoUserArticle">
        <img src="<?= $picture['user_photo']; ?>" alt="">
      </div>
          
          <p><?= $picture['user_pseudo']; ?></p>
        </div>
        <p class="datePhotos"><?= date_format(date_create($picture['created_at']), "d M Y")  ?></p>
      </div>
      <hr>
      
        <img src="<?= $picture['src'] ?>" alt="<?= $picture['title'] ?>" class="imgArticle">
      
      <p class="titrePhoto"><?= $picture['title'] ?></p>
      <p class="descritpionPhoto"><?= $picture['description'] ?></p>

      <!-- Social -->
      <div class="social">


        <!-- likes -->
        <?php if (isset($_SESSION['pseudo'])) : ?>

          <?php if (Likes::cntUnlikes($picture['id']) == false) : ?>
            <div class="like"><button class="likeBtn" data-pictureid="<?= $picture['id']; ?>">Like </button>
              <p><?= $picture['nbrLikes']; ?></p>
            </div>
          <?php else : ?>
            <div class="like">
              <button class="unlikeBtn" data-pictureid="<?= $picture['id']; ?>">Like</button>
              <p><?= $picture['nbrLikes']; ?></p>
            </div>
          <?php endif; ?>
        <?php else : ?>
          <button class="likeBtn" disabled>Like <?= $picture['nbrLikes']; ?></button>
        <?php endif; ?>


        <!-- commentaires -->




        <?php if ((int)$picture['nbrCom'] > 1) { ?>
          <a class="btnCom" data-bs-toggle="collapse" href="#collapseCommentaires<?= $picture['id'] ?>"><?= $picture['nbrCom'] ?> commentaires </a>
        <?php } else { ?>
          <a class="btnCom" data-bs-toggle="collapse" href="#collapseCommentaires<?= $picture['id'] ?>"><?= $picture['nbrCom'] ?> commentaire </a>
        <?php } ?>
      </div>

      <div class="commentaireArticle collapse" id="collapseCommentaires<?= $picture['id'] ?>">
        <form method="POST" action="?page=comment" class="formCom" id="form_comment" data-picture-id="<?= $picture['id']; ?>">

          <div class="inputCom">
            <?php if (isset($_SESSION['pseudo'])) { ?>

              <img src="<?= $_SESSION['photo']; ?>" alt="" class="userPhotoCom">
              <textarea name="com" class="commentaire" placeholder="Commentez"></textarea>
              <input type="hidden" name="id_post" value="<?= $picture['id']; ?>">
              <input type="submit" name="valider" value="OK" class="btnSend" />




            <?php } else { ?>
              <p class="unconnectCom">Connectez-vous pour commenter </p>
            <?php }; ?>
          </div>
        </form>

        <!-- génération commentaires -->
        <?php $comments = comment::getAllComment($picture['id'])[0]; ?>
        <div class="commentaires" id="commentaires<?= $picture['id'] ?>" >
        <?php foreach ($comments as $comment) : ?>
            <div class="comContent" id="commentaire_<?= $comment['comment_id'] ?>">
              <img src="<?= $comment['user_photo']; ?>" alt="" class="userPhotoCom">
              <div class="idcom">
                <div class="cadreCom">
                  <p class="userComment"><?= $comment['user_pseudo']; ?></p>
                  <p class="textComment"><?= $comment['com']; ?></p>
                </div>
                <div class="optionCom">
                  <p class="dateComment"><?= $comment['date_com']; ?></p>
                  <?php if (isset($_SESSION['id']) && (int)$_SESSION['id'] === (int)$comment['id_user']) { ?>
                    <form method="POST" id="form_delete">
                      <input type="hidden" name="comment_id" value="<?= $comment['comment_id']; ?>">
                      <input type="submit" name="supprimer" value="Supprimer" class="supprCom" data-commentid="<?= $comment['comment_id'];?>">
                    </form>
                  <?php }; ?>
                </div>
              </div>
            </div>
            <?php endforeach; ?>
          </div>
      </div>

    </div>
  <?php endforeach; ?>
</div>
<?php } ?>


<script>
  $(document).ready(function() {
    $('.supprCom').click(function(event) {
            event.preventDefault();


            let button = $(this);
            let commentId = button.data('commentid');
            let commentDelete = document.querySelector('#commentaire_' + commentId)
            commentDelete.classList.add('transitionUnfollow');
            setTimeout(() => {
                commentDelete.style.display = "none";
            }, 300);

            $.ajax({
                type: 'POST',
                url: '?page=home',
                data: {
                  commentId: commentId,
                },
            });
        });

    $('.likeBtn, .unlikeBtn').click(function(event) {
      event.preventDefault();

      let button = $(this);
      let pictureId = button.data('pictureid');
      let action = button.hasClass('likeBtn') ? 'like' : 'unlike';

      $.ajax({
        type: 'POST',
        url: '?page=like',
        data: {
          id_picture: pictureId,
          action: action
        },
        dataType: 'json',
        success: function(response) {
          console.log(response);

          button.next('p').text(response.likes);

          if (button.hasClass('likeBtn')) {
            button.text('Like');
            button.removeClass('likeBtn').addClass('unlikeBtn');
          } else {
            button.text('Like');
            button.removeClass('unlikeBtn').addClass('likeBtn');
          }
        }
      });
    });


    $('.formCom').submit(function(event) {
      event.preventDefault();

      console.log('Form submitted');

      let form = $(this);
      let pictureId = form.data('picture-id');
      let commentText = form.find('textarea[name="com"]').val();

      form.find('textarea[name="com"]').val('');

      console.log(pictureId);
      console.log(commentText);

      $.ajax({
        type: 'POST',
        url: '?page=comment',
        data: {
          id_picture: pictureId,
          comment: commentText
        },
        dataType: 'json',
        success: function(response) {
          // console.log(response);
          console.log(response);
          let com = response.newcomment[0].com;
          let pseudo = response.newcomment[0].user_pseudo;
          let photo = response.newcomment[0].user_photo;
          let date = response.newcomment[0].date_com;
          let idUser = response.newcomment[0].id_user;
          let commentId = response.newcomment[0].comment_id;
          

          let newComment = insertCom(pictureId,photo,pseudo,com,date,idUser,commentId)
          $('#commentaires'+pictureId).prepend(newComment)

          

        }
      });
    });

    function insertCom(article,photo,pseudo,com,date,idUser,commentId){
      let commentElement = document.createElement('div');
    commentElement.className = 'comContent';
    commentElement.id = 'commentaire' + article;

    commentElement.innerHTML = `
        
            <img src="${photo}" alt="" class="userPhotoCom">
            <div class="idcom">
                <div class="cadreCom">
                    <p class="userComment">${pseudo}</p>
                    <p class="textComment">${com}</p>
                </div>
                <div class="optionCom">
                    <p class="dateComment">${date}</p>
                    <?php if (isset($_SESSION['id']) && (int)$_SESSION['id'] === (int)$comment['id_user']) { ?>
                    <form method="POST" id="form_delete">
                      <input type="hidden" name="comment_id" value="${commentId}">
                      <input type="submit" name="supprimer" value="Supprimer" class="supprCom" data-commentid="${commentId}">
                    </form>
                  <?php }; ?>
                </div>
            </div>
        
    `;

    return commentElement;
    }

  });
</script>