
<div class="formlog">
    <div class="connexion">
        <h1>Connexion</h1>

        <form style="margin:5% 25%" method="POST">
            <div class="mb-3">
                <label for="pseudo" class="form-label">Pseudo:</label>
                <input type="text" class="form-control" id="pseudo" name="pseudo" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Mot de passe:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <input type="submit" name="submit" class="form-control btn-connexion" value="Se connecter">

        </form>
        
       
        <p style="color:red;"><?= $alertConnect;?></p>

        <?php if(!empty($success)){?>
        <p style="color: green;"><?= $success;?></p>
        <?php } else { ?>
        <p style="color: gray;">Vous devez avoir un compte pour profiter de notre site</p>
        <?php }?>
    </div>
    <hr>
    <div class="inscription">
        <h1>Inscription</h1>

        <form style="margin:5% 25%" method="POST">

            <div class="mb-3">
                <label for="firstname" class="form-label">Prénom:</label>
                <input type="text" class="form-control"  name="firstname" required>
            </div>
            <div class="mb-3">
                <label for="name" class="form-label">Nom:</label>
                <input type="text" class="form-control"  name="name" required>
            </div>
            <div class="mb-3">
                <label for="pseudo" class="form-label">Pseudo: <span style="color: red;"><?= $errorPseudo ?></span></label>
                <input type="text" class="form-control"  name="pseudo" required>
            </div>
            <div class="mb-3">
                <label for="gender" class="form-label">Genre:</label>
                <select class="form-control" name="gender" required>
                    <option value="homme">Homme</option>
                    <option value="femme">Femme</option>
                    <option value="autres">Autres</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="mail" class="form-label">E-mail: <span style="color: red;"><?= $errorMail ?></span></label>
                <input type="email" class="form-control" id="mail" name="mail" required>
            </div>
            <div class="mb-3">
            
                <label for="password" class="form-label">Mot de passe: <span style="color: red;"><?= $errorPass ?></span></label>
                <input type="password" class="form-control"  name="password" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Confirmer le mot de passe: <span style="color: red;"><?= $errorPass ?></span></label>
                <input type="password" class="form-control"  name="confirmPassword" required>
            </div>
            

            <input type="submit" name="inscription" class="form-control btn-inscription" value="S'inscrire">
        </form>
    </div>
</div>